export {default as CategorySwitch} from './CategorySwitch/index.vue'
export {default as CategoryFilter} from './CategoryFilter/index.vue'
export {default as GoodsNormalSale} from './GoodsNormalSale/index.vue'
export {default as GoodsHotSale} from './GoodsHotSale/index.vue'
export {default as GoodsMore} from './GoodsMore/index.vue'
